name: FoundryVTT-gl CI

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      - name: Create installable system zip file
        run: zip -r foundryvtt-gl.zip module.json dist

      - name: Create release
        id: create_versioned_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'module.json,foundryvtt-gl.zip'

