name: FoundryVTT-gl CI

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      - name: Get current date
        shell: bash
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%m')"

      - name: Create installable system zip file
        run: zip -r foundryvtt-gl.zip module.json dist

      - name: Create release
        id: create_versioned_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.get-date.outputs.date }}
          artifacts: 'module.json,foundryvtt-gl.zip'
